import { LegalPage, H2 } from '@/components/legal/LegalPage';

const EFFECTIVE_DATE = 'Effective 26 April 2026';

export default function PrivacyPage() {
  return (
    <LegalPage title="Privacy" subtitle={EFFECTIVE_DATE}>
      <p>
        This page describes what Meridian Edge collects when you use the platform, why we collect
        it, and how to remove it. We hold the minimum needed to operate trading on your behalf,
        and we never sell or rent your data.
      </p>

      <H2>What we collect</H2>
      <p>
        <strong>Account data</strong> — email, display name, optional phone number. Used to sign
        you in and reach you about account-critical events (security, billing, outages).
      </p>
      <p>
        <strong>Exchange credentials</strong> — Binance API key/secret, encrypted at rest with a
        deployment-scoped key. We never display the secret again after submission. We strongly
        recommend disabling withdrawal permissions on the API key; the connect-account dialog
        documents the safe configuration.
      </p>
      <p>
        <strong>Trading state</strong> — your open and closed positions, P&amp;L, strategy
        configurations, backtests, audit log of security-sensitive changes. This is generated by
        your use of the platform and is required to render the dashboard.
      </p>
      <p>
        <strong>Diagnostic snapshots</strong> — only when you submit one explicitly via
        Settings &rarr; Help &amp; support. The snapshot captures app version, your user id, and
        the page you were on. It never includes your token, password, or API credentials.
      </p>
      <p>
        <strong>Operational logs</strong> — request timestamps, endpoint paths, response codes.
        Retained 30 days for debugging and abuse prevention.
      </p>

      <H2>What we don&apos;t collect</H2>
      <p>
        We do not run third-party trackers, advertising pixels, or analytics SDKs. We do not
        sell, share, or license any of the data above to third parties.
      </p>

      <H2>Where it lives</H2>
      <p>
        Application data is stored on our managed PostgreSQL cluster. Backups are encrypted at
        rest and retained 14 days. Server access is restricted to engineering staff under
        named accounts and audited.
      </p>

      <H2>Your rights</H2>
      <p>
        You can export your full account state on request. You can permanently delete your
        account, which removes credentials, profile, and personally-identifying data.
        Trade history is retained in pseudonymous form for regulatory and accounting reasons.
      </p>
      <p>
        For requests or questions, reach us via Settings &rarr; Help &amp; support, or email
        privacy@blackheart.app.
      </p>
    </LegalPage>
  );
}
